### ISSUE TITLE
ex does not like rules including unused variables

### ISSUE THREAD

**Issue by mvdan** [rsc/rf#4]
For example, the script below could be used to simplify obtaining a map key, rewriting `foo, _ := bar[idx]` into `foo := bar[idx]`:

```
$ rf 'ex { var m map[string]int; var s string; x, _ := m[s] -> x := m[s] }'
ex.go:6:2: x declared but not used
ex.go:7:3: x declared but not used
ex: errors in example:
	package ipld
	func _() {
	var m map[string]int
	var s string
	{
	{x, _ := m[s] }
	{ x := m[s]}
	}
	}
```

This fails, because the rule snippet alone does not use the declared variable. Perhaps we should turn off such "not used" errors when loading rules, or perhaps we should add a special way to write rules to match declarations. A special way could then also match `var foo, _ = bar[idx]` and `foo, _ = bar[idx]`, for example.

**Comment by mvdan** [comment]
Also, how open are you to contributions and ideas? I'd like to start using rf for some backwards-incompatible API changes, as a sort of custom `go fix`. I have some experience in this field via https://github.com/mvdan/gogrep, which supports rewriting entire chunks of statements, declarations, etc.

**Comment by mdempsky** [comment]
I'd be fine with changing unused variables into a warning rather than an error.

**Comment by mvdan** [comment]
@mdempsky thanks! Would a PR here be welcome, or is GitHub just a mirror?

**Comment by mdempsky** [comment]
PR is fine.
